# This script trains a BERT-based multi-label text classifier on task descriptions to predict associated task labels.


# --------------------- IMPORTS ---------------------

import sys
# Block DeepSpeed import to prevent environment crash
sys.modules["deepspeed"] = None

import os
# Disable tokenizer parallelism (fixes warnings on Jean Zay)
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import ast
import random
import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_linear_schedule_with_warmup
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, precision_score, recall_score
from tqdm.auto import tqdm

# To ignore warnings (not print them in the out file)
import warnings
warnings.filterwarnings("ignore")

from transformers import logging
logging.set_verbosity_error()


# --------------------- CONFIG ---------------------

MODEL_PATH = os.path.join(os.environ["DSDIR"], "HuggingFace_Models/bert-base-uncased")
TRAIN_TSV = "../../data/attributions/2022_attributions/bert/bert_training_data/merged_tasks_2023_24_25.tsv"
OUTPUT_DIR = "../../data/attributions/2022_attributions/bert/bert_training_data/model_results"
MODEL_OUTPUT_DIR = f"{OUTPUT_DIR}/trained_model"

loss_history = []

BATCH_SIZE = 16 # number of training examples per batch

EPOCHS = 3 # number of times the model sees the full training set

LEARNING_RATE = 2e-5 

TASK_LABELS = [
    "software","conceptualization","public engagement","writing","investigation",
    "hardware","project administration","entrepreneurship","fundraising",
    "background research","safety","analysis","visualization","data curation",
] # without "lab maintenance"

LABEL2ID = {label: i for i, label in enumerate(TASK_LABELS)} #give task names ids
# for example, for a task description that contains tasks ["software", "writing"] --> [1,0,0,1,0,0,...,0]

MAX_LENGTH = 512 # for tokenizer, max length of tokens (for TaxDescription length for example), 512 is BERT's maximum

# Force PyTorch to use standard math that is stable
if torch.cuda.is_available():
    torch.backends.cuda.enable_flash_sdp(False)
    torch.backends.cuda.enable_mem_efficient_sdp(False)
    torch.backends.cuda.enable_math_sdp(True)

SEED = 42

# Seed
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)


# --------------------- DATA ---------------------

df = pd.read_csv(
    TRAIN_TSV, sep="\t"
)

# Convert task lists to multi-hot vectors for multi-label classification (e.g. ["investigation", "writing"] --> [0,0,0,1,1,0,...,0])
def tasks_to_multihot(tasks):
    vec = [0]*len(TASK_LABELS)
    if isinstance(tasks, str):  # if "Tasks" column is a string like '["investigation", "writing"]':
        tasks = ast.literal_eval(tasks)
    for t in tasks:
        vec[LABEL2ID[t]] = 1
    return vec

df["Labels"] = df["Tasks"].apply(tasks_to_multihot)


# TRAIN-VAL-TEST SPLIT

task_descriptions  = df["TaskDescription"].tolist()
task_labels = df["Labels"].tolist()

# New rows to always include in TRAIN set - definitions of labels from the survey
# Won't change much because its only 14 rows
new_rows_df = pd.DataFrame(
    [
        ["Developing, implementing, and/or testing computer programs and code", ["software"]],
        ["Brainstorming and developing ideas for the project", ["conceptualization"]],
        ["Preparing and/or implementing tools/activities to engage the broader community", ["public engagement"]],
        ["Writing, reviewing or editing content for the wiki or other documents to be shared outside the team", ["writing"]],
        ["Performing the experiments and/or collecting data/evidence", ["investigation"]],
        # ["Cleaning, organizing, and preparing the research facilities or lab", ["lab maintenance"]], # lab maintenance excluded from labels
        ["Designing, building, and/or testing mechanical, electrical, or optical hardware systems", ["hardware"]],
        ["Managing and coordinating the project activities, planning, and execution", ["project administration"]],
        ["Developing business models and other commercially relevant materials or activities", ["entrepreneurship"]],
        ["Raising money, in-kind donations of materials, and/or services for the team’s activities", ["fundraising"]],
        ["Reading peer-reviewed scientific research articles, white papers, regulations/guidelines, and other documents", ["background research"]],
        ["Performing activities to ensure compliance with the safety guidelines or requirements of iGEM, your institution, and/or government", ["safety"]],
        ["Analyzing data generated by your team, another iGEM team (current or previous), and/or from literature as needed for your project", ["analysis"]],
        ["Preparation, creation and/or presentation of the work including data visualization, user interfaces, videos and other graphics, design.", ["visualization"]],
        ["Annotating (producing metadata), cleaning, and maintaining research data for your team’s project and for future use by other iGEM teams or members of the synthetic biology", ["data curation"]],
    ],
    columns=["TaskDescription", "Tasks"]
)

# add labels to the new rows
new_rows_df["Labels"] = new_rows_df["Tasks"].apply(tasks_to_multihot)

# Train df and Temp df(val+test) split
# X - the task descriptions, y - the task labels
train_raw_descriptions, temp_raw_descriptions, train_labels, temp_labels = train_test_split(task_descriptions, task_labels, test_size=0.2, random_state=SEED)

# append official rows to TRAIN only
train_raw_descriptions += new_rows_df["TaskDescription"].tolist()
train_labels += new_rows_df["Labels"].tolist()

# Temp df into Val and Test (half-half) split
val_raw_descriptions, test_raw_descriptions, val_labels, test_labels = train_test_split(temp_raw_descriptions, temp_labels, test_size=0.5, random_state=SEED)


# --------------------- TOKENIZER ---------------------

print("\nTokenizing text...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)

# Function to tokenize Task Descriptions texts
def tokenize(texts):
    return tokenizer(
        texts,
        truncation=True,
        padding="max_length",
        max_length=MAX_LENGTH
    )

train_encodings = tokenize(train_raw_descriptions)
val_encodings   = tokenize(val_raw_descriptions)
test_encodings  = tokenize(test_raw_descriptions)


# --------------------- DATASET CLASS ---------------------

class TextClassifierDataset(Dataset): # creates a dataset type compatible with PyTorch’s DataLoader
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx): # how PyTorch retrieves one training example from the dataset
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.float) #labels should be float because the loss is Binary Cross Entropy with Logits which expects floats
        return item

train_dataset = TextClassifierDataset(train_encodings, train_labels) # train_encodings are the encoded task description texts in the train df, while train_labels are the task labels in the train df
val_dataset = TextClassifierDataset(val_encodings, val_labels)
test_dataset = TextClassifierDataset(test_encodings, test_labels)


# --------------------- LOAD MODEL ---------------------

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\nUsing device: {device}")

print("\nLoading model...")
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_PATH,
    problem_type="multi_label_classification",
    num_labels=len(TASK_LABELS),
    attn_implementation="eager"  # Force Hugging Face to use standard PyTorch
).to(device) # move model to GPU if available


# --------------------- HELPER FUNCTIONS FOR TRAINING ---------------------

# IMPORTANT note: Some of the following code is written for manual training without using the Trainer class from transformers because the class gives import errors on Jean Zay (DeepSpeed + Triton erros on pytorch-gpu/py3/2.6.0)
# If importing Trainer and TrainingArguments from transformers works, code can be simplified 
# Using a module with a version older than 2.6.0 causes a ValueError instead

# Function to compute POS WEIGHT - to be used in the loss function
# It tells loss: Positive examples are more important than negative examples for this label (so rare labels get amplified)
def compute_pos_weight(train_labels, device):

    Y_train = np.stack(train_labels)

    pos_counts = Y_train.sum(axis=0) # positives per label
    neg_counts = Y_train.shape[0] - pos_counts # negatives per label

    # Avoid division by 0 if a label has 0 positives - but it will always predict 0 for that label
    pos_weight = neg_counts / np.clip(pos_counts, 1, None)

    return torch.tensor(pos_weight, dtype=torch.float).to(device)

# Function for training one epoch
# It trains the model on the full training DataLoader once and returns average training loss
def train_one_epoch(model, loader, optimizer, scheduler, loss_fn, device):
    model.train()
    total_loss = 0

    # Add tqdm progress bar (I added it only for the training loop)
    for batch in tqdm(loader, desc="Training", leave=True):
        optimizer.zero_grad()

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device).float()

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits

        loss = loss_fn(logits, labels)
        loss.backward()

        optimizer.step()
        scheduler.step()

        total_loss += loss.item()

    return total_loss / len(loader)


# Function for evaluation of loss (validation and test)
@torch.no_grad() # disables gradient tracking (not needed for val and test) to save memory and speed up evaluation
def evaluate(model, loader, loss_fn, device):
    model.eval()
    total_loss = 0

    for batch in loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device).float()

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits

        loss = loss_fn(logits, labels)
        total_loss += loss.item()

    return total_loss / len(loader) # average loss over all batches


# Helper functions for TUNING THRESHOLDS

# Function to get predicted probabilities on the validation set + true labels (to be used in threshold tuning)
@torch.no_grad()
def get_probs_and_labels(model, loader, device):
    model.eval()
    all_probs = []
    all_labels = []

    for batch in loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].cpu().numpy()  # keep on CPU for numpy ops

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits

        probs = torch.sigmoid(logits).cpu().numpy()  # convert logits -> probabilities

        all_probs.append(probs)
        all_labels.append(labels)

    all_probs = np.vstack(all_probs)    # shape: (N, num_labels)
    all_labels = np.vstack(all_labels)  # shape: (N, num_labels)
    return all_probs, all_labels

# Function to tune best threshold per label (maximize F1)
def tune_thresholds_per_label(val_probs, val_labels, thresholds=None):
    if thresholds is None:
        thresholds = np.arange(0.1, 0.91, 0.05) # trying thresholds between 0.1 and 0.95 with step size 0.05 between them

    num_labels = val_labels.shape[1]
    best_thresholds = np.zeros(num_labels)

    for j in range(num_labels):
        best_t = 0.5
        best_f1 = -1
        y_true = val_labels[:, j].astype(int)

        for t in thresholds:
            y_pred = (val_probs[:, j] >= t).astype(int)
            f1 = f1_score(y_true, y_pred, zero_division=0)

            if f1 > best_f1:
                best_f1 = f1
                best_t = t

        best_thresholds[j] = best_t

    return best_thresholds


# Function to apply tuned thresholds to test predictions later
# Converts probabilities to final 0/1 predictions using a per-label threshold 
# e.g. if probability for conceptualization > conceptualization's best threshold --> conceptualization is 1)
def apply_thresholds(probs, thresholds):
    # Make thresholds shape (1, num_labels) so it can compare against all rows
    thresholds_matrix = thresholds.reshape(1, -1)

    # Compare each probability to its label threshold -> True/False
    meets_threshold = probs >= thresholds_matrix

    # Convert True/False to 1/0 integers
    preds = meets_threshold.astype(int)

    return preds


# --------------------- TRAINING ---------------------

# DataLoader
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=4) # num_workers controls how many CPU processes are used to load and prepare batches in parallel
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=4)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=4)


# Loss function - Binary Cross Entropy with Logits using pos_weight
pos_weight = compute_pos_weight(train_labels, device)
loss_fn = torch.nn.BCEWithLogitsLoss(pos_weight=pos_weight)


# Optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)


# Total number of weight-update steps during training (batches per epoch × number of epochs)
total_steps = len(train_loader) * EPOCHS

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),  # warm up the learning rate for the first 10% of steps (stabilizes early training) - Trainer class would handle this
    num_training_steps=total_steps            # then gradually decrease the learning rate until training ends
)

# Full Training Loop

print("\nStarting Manual Training Loop...")

loss_history = []

for epoch in range(EPOCHS):
    train_loss = train_one_epoch(model, train_loader, optimizer, scheduler, loss_fn, device)
    val_loss = evaluate(model, val_loader, loss_fn, device)

    loss_history.append({
        "epoch": epoch + 1,
        "train_loss": train_loss,
        "val_loss": val_loss
    })

print("\nModel trained")


# --------------------- RESULTS --------------------- 

# Check output dir exists
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Save LOSS HISTORY
loss_df = pd.DataFrame(loss_history)
loss_df.to_csv(f"{OUTPUT_DIR}/loss_history.csv", index=False)
print(f"\nSaved loss history to: {OUTPUT_DIR}/loss_history.csv")


# THRESHOLD TUNING on validation set

val_probs, val_true = get_probs_and_labels(model, val_loader, device)
best_thresholds = tune_thresholds_per_label(val_probs, val_true)

thresholds_df = pd.DataFrame({
    "label": TASK_LABELS,
    "best_threshold": best_thresholds,
})
thresholds_df.to_csv(f"{OUTPUT_DIR}/best_thresholds.csv", index=False)
print(f"\nSaved best thresholds to {OUTPUT_DIR}/best_thresholds.csv")


# METRICS

# Function that returns overall and per-label metrics
def compute_multilabel_metrics(y_true, y_pred, label_names):
    overall_metrics = {
        "micro_precision": precision_score(y_true, y_pred, average="micro", zero_division=0),
        "micro_recall":    recall_score(y_true, y_pred, average="micro", zero_division=0),
        "micro_f1":        f1_score(y_true, y_pred, average="micro", zero_division=0),
        "macro_precision": precision_score(y_true, y_pred, average="macro", zero_division=0),
        "macro_recall":    recall_score(y_true, y_pred, average="macro", zero_division=0),
        "macro_f1":        f1_score(y_true, y_pred, average="macro", zero_division=0),
    }

    rows = []
    for j, label in enumerate(label_names):
        yt = y_true[:, j]
        yp = y_pred[:, j]

        tp = int(((yt == 1) & (yp == 1)).sum())
        fp = int(((yt == 0) & (yp == 1)).sum())
        fn = int(((yt == 1) & (yp == 0)).sum())
        tn = int(((yt == 0) & (yp == 0)).sum())

        rows.append({
            "label": label,
            "support_pos": int((yt == 1).sum()),
            "tp": tp,
            "fp": fp,
            "fn": fn,
            "tn": tn,
            "precision": precision_score(yt, yp, zero_division=0),
            "recall": recall_score(yt, yp, zero_division=0),
            "f1": f1_score(yt, yp, zero_division=0),
        })

    per_label_df = pd.DataFrame(rows)
    return overall_metrics, per_label_df

# Function to:
# 1. run the trained model on a dataset split (train/val/test)
# 2. turn probabilities into 0/1 predictions using thresholds 
# 3. compute metrics reusing previous function
# 4. save everything to CSV
def evaluate_split_and_save(split, loader, model, device, thresholds, label_names, output_dir):
    probs, true = get_probs_and_labels(model, loader, device)
    preds = apply_thresholds(probs, thresholds)

    overall_metrics, per_label_df = compute_multilabel_metrics(
        true.astype(int),
        preds.astype(int),
        label_names
    )

    # Save per-label metrics 
    per_label_df.to_csv(f"{output_dir}/{split}_per_label_metrics.csv", index=False)
    print(f"\nSaved per-label metrics to: {OUTPUT_DIR}/{split}_per_label_metrics.csv")

    return {"split": split, **overall_metrics} # merging two dictionaries


# Collect and save one combined overall_metrics.csv for splits: train, val, test
train_metrics = evaluate_split_and_save(
    "train", train_loader, model, device, best_thresholds, TASK_LABELS, OUTPUT_DIR
)
val_metrics = evaluate_split_and_save(
    "val", val_loader, model, device, best_thresholds, TASK_LABELS, OUTPUT_DIR
)
test_metrics = evaluate_split_and_save(
    "test", test_loader, model, device, best_thresholds, TASK_LABELS, OUTPUT_DIR
)

overall_metrics_df = pd.DataFrame([train_metrics, val_metrics, test_metrics])
overall_metrics_df.to_csv(f"{OUTPUT_DIR}/overall_metrics.csv", index=False)
print(f"\nSaved overall metrics to: {OUTPUT_DIR}/overall_metrics.csv")


# Save MODEL and TOKENIZER

model.save_pretrained(MODEL_OUTPUT_DIR)
tokenizer.save_pretrained(MODEL_OUTPUT_DIR)

print(f"\nSaved model and tokenizer to: {MODEL_OUTPUT_DIR}")
